//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguageMVCNET6.Resources.Views.Countries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguageMVCNET6.Resources.Views.Countries.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngiltere.
        /// </summary>
        public static string view_countries_ingiltere_pc {
            get {
                return ResourceManager.GetString("view.countries.ingiltere_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;display: inline;color: crimson;&quot;&gt;İNGİLTERE&lt;p&gt;.
        /// </summary>
        public static string view_countries_ingiltere_uc {
            get {
                return ResourceManager.GetString("view.countries.ingiltere_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusya.
        /// </summary>
        public static string view_countries_rusya_pc {
            get {
                return ResourceManager.GetString("view.countries.rusya_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;display: inline;color: crimson;&quot;&gt;RUSYA&lt;p&gt;.
        /// </summary>
        public static string view_countries_rusya_uc {
            get {
                return ResourceManager.GetString("view.countries.rusya_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkiye.
        /// </summary>
        public static string view_countries_turkiye_pc {
            get {
                return ResourceManager.GetString("view.countries.turkiye_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;display: inline;color: crimson;&quot;&gt;TÜRKİYE&lt;p&gt;.
        /// </summary>
        public static string view_countries_turkiye_uc {
            get {
                return ResourceManager.GetString("view.countries.turkiye_uc", resourceCulture);
            }
        }
    }
}
