//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguageMvc2.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguageMvc2.Resources.Controllers.HomeController", typeof(HomeController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Core ile &lt;a href=&quot;https://docs.microsoft.com/aspnet/core&quot;&gt;Web uygulamaları oluşturma hakkında bilgi edinin&lt;/a&gt;..
        /// </summary>
        public static string home_description_pc {
            get {
                return ResourceManager.GetString("home_description_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ana sayfa.
        /// </summary>
        public static string home_lc {
            get {
                return ResourceManager.GetString("home_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string home_pc {
            get {
                return ResourceManager.GetString("home_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANA SAYFA.
        /// </summary>
        public static string home_uc {
            get {
                return ResourceManager.GetString("home_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingilizce.
        /// </summary>
        public static string ingilizce_lc {
            get {
                return ResourceManager.GetString("ingilizce_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string ingilizce_pc {
            get {
                return ResourceManager.GetString("ingilizce_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNGİLİZCE.
        /// </summary>
        public static string ingilizce_uc {
            get {
                return ResourceManager.GetString("ingilizce_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kazakça.
        /// </summary>
        public static string kazakca_lc {
            get {
                return ResourceManager.GetString("kazakca_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakça.
        /// </summary>
        public static string kazakca_pc {
            get {
                return ResourceManager.GetString("kazakca_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAZAKÇA.
        /// </summary>
        public static string kazakca_uc {
            get {
                return ResourceManager.GetString("kazakca_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turkiye.png.
        /// </summary>
        public static string LanguageImage {
            get {
                return ResourceManager.GetString("LanguageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gizlilik.
        /// </summary>
        public static string privacy_lc {
            get {
                return ResourceManager.GetString("privacy_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik.
        /// </summary>
        public static string privacy_pc {
            get {
                return ResourceManager.GetString("privacy_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gizlilik politikası.
        /// </summary>
        public static string privacy_policy_lc {
            get {
                return ResourceManager.GetString("privacy_policy_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası.
        /// </summary>
        public static string privacy_policy_pc {
            get {
                return ResourceManager.GetString("privacy_policy_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİZLİLİK POLİTİKASI.
        /// </summary>
        public static string privacy_policy_uc {
            get {
                return ResourceManager.GetString("privacy_policy_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİZLİLİK.
        /// </summary>
        public static string privacy_uc {
            get {
                return ResourceManager.GetString("privacy_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rusça.
        /// </summary>
        public static string rusca_lc {
            get {
                return ResourceManager.GetString("rusca_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusça.
        /// </summary>
        public static string rusca_pc {
            get {
                return ResourceManager.GetString("rusca_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUSÇA.
        /// </summary>
        public static string rusca_uc {
            get {
                return ResourceManager.GetString("rusca_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string test_lc {
            get {
                return ResourceManager.GetString("test_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string test_pc {
            get {
                return ResourceManager.GetString("test_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string test_uc {
            get {
                return ResourceManager.GetString("test_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to türkçe.
        /// </summary>
        public static string turkce_lc {
            get {
                return ResourceManager.GetString("turkce_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string turkce_pc {
            get {
                return ResourceManager.GetString("turkce_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜRKÇE.
        /// </summary>
        public static string turkce_uc {
            get {
                return ResourceManager.GetString("turkce_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoş geldiniz.
        /// </summary>
        public static string welcome_lc {
            get {
                return ResourceManager.GetString("welcome_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldiniz.
        /// </summary>
        public static string welcome_pc {
            get {
                return ResourceManager.GetString("welcome_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOŞ GELDİNİZ.
        /// </summary>
        public static string welcome_uc {
            get {
                return ResourceManager.GetString("welcome_uc", resourceCulture);
            }
        }
    }
}
