//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguageMvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguageMvc.Resources.Language - Copy", typeof(Language___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingilizce.
        /// </summary>
        public static string ingilizce_lc {
            get {
                return ResourceManager.GetString("ingilizce_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string ingilizce_pc {
            get {
                return ResourceManager.GetString("ingilizce_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNGİLİZCE.
        /// </summary>
        public static string ingilizce_uc {
            get {
                return ResourceManager.GetString("ingilizce_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kazakça.
        /// </summary>
        public static string kazakca_lc {
            get {
                return ResourceManager.GetString("kazakca_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakça.
        /// </summary>
        public static string kazakca_pc {
            get {
                return ResourceManager.GetString("kazakca_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAZAKÇA.
        /// </summary>
        public static string kazakca_uc {
            get {
                return ResourceManager.GetString("kazakca_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rusça.
        /// </summary>
        public static string rusca_lc {
            get {
                return ResourceManager.GetString("rusca_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusça.
        /// </summary>
        public static string rusca_pc {
            get {
                return ResourceManager.GetString("rusca_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUSÇA.
        /// </summary>
        public static string rusca_uc {
            get {
                return ResourceManager.GetString("rusca_uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to türkçe.
        /// </summary>
        public static string turkce_lc {
            get {
                return ResourceManager.GetString("turkce_lc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string turkce_pc {
            get {
                return ResourceManager.GetString("turkce_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜRKÇE.
        /// </summary>
        public static string turkce_uc {
            get {
                return ResourceManager.GetString("turkce_uc", resourceCulture);
            }
        }
    }
}
